// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgramacionV.Api.Data;

#nullable disable

namespace ProgramacionV.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913223952_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ProgramacionV.Api.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgramaAcademicoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProgramaAcademicoId");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "ana.torres@universidad.edu.co",
                            Documento = "1001001001",
                            Nombre = "Ana Torres",
                            ProgramaAcademicoId = 1,
                            Telefono = "3001111111"
                        },
                        new
                        {
                            Id = 2,
                            Correo = "carlos.gomez@universidad.edu.co",
                            Documento = "1001001002",
                            Nombre = "Carlos Gómez",
                            ProgramaAcademicoId = 1,
                            Telefono = "3002222222"
                        },
                        new
                        {
                            Id = 3,
                            Correo = "laura.perez@universidad.edu.co",
                            Documento = "1001001003",
                            Nombre = "Laura Pérez",
                            ProgramaAcademicoId = 1,
                            Telefono = "3003333333"
                        },
                        new
                        {
                            Id = 4,
                            Correo = "miguel.ramirez@universidad.edu.co",
                            Documento = "1001001004",
                            Nombre = "Miguel Ramírez",
                            ProgramaAcademicoId = 2,
                            Telefono = "3004444444"
                        },
                        new
                        {
                            Id = 5,
                            Correo = "sofia.martinez@universidad.edu.co",
                            Documento = "1001001005",
                            Nombre = "Sofía Martínez",
                            ProgramaAcademicoId = 2,
                            Telefono = "3005555555"
                        });
                });

            modelBuilder.Entity("ProgramacionV.Api.Models.ProgramaAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProgramasAcademicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "SIS",
                            Nombre = "Ingeniería de Sistemas"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "ADM",
                            Nombre = "Administración de Empresas"
                        });
                });

            modelBuilder.Entity("ProgramacionV.Api.Models.Estudiante", b =>
                {
                    b.HasOne("ProgramacionV.Api.Models.ProgramaAcademico", "ProgramaAcademico")
                        .WithMany("Estudiantes")
                        .HasForeignKey("ProgramaAcademicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramaAcademico");
                });

            modelBuilder.Entity("ProgramacionV.Api.Models.ProgramaAcademico", b =>
                {
                    b.Navigation("Estudiantes");
                });
#pragma warning restore 612, 618
        }
    }
}
